// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD14Q0KeuYs0CHDUsj2yN767zZkZ-SWjP0',
    appId: '1:449239285389:web:3e428596bf8ef4648facc4',
    messagingSenderId: '449239285389',
    projectId: 'inspecto-shield',
    authDomain: 'inspecto-shield.firebaseapp.com',
    storageBucket: 'inspecto-shield.firebasestorage.app',
    measurementId: 'G-HEXRG216F1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPL9nbjeCRbsGFFHNz7rxZtfqZ66cTCG4',
    appId: '1:449239285389:android:85c436dd5bf205ef8facc4',
    messagingSenderId: '449239285389',
    projectId: 'inspecto-shield',
    storageBucket: 'inspecto-shield.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpT3L8avvV2EV62OGrGX1ptRLf8NLQBFA',
    appId: '1:449239285389:ios:87d59d58eaa7cd9d8facc4',
    messagingSenderId: '449239285389',
    projectId: 'inspecto-shield',
    storageBucket: 'inspecto-shield.firebasestorage.app',
    iosBundleId: 'com.inspecto.shield.hashpixels',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpT3L8avvV2EV62OGrGX1ptRLf8NLQBFA',
    appId: '1:449239285389:ios:93cbbe1faa7bfdf58facc4',
    messagingSenderId: '449239285389',
    projectId: 'inspecto-shield',
    storageBucket: 'inspecto-shield.firebasestorage.app',
    iosBundleId: 'com.example.hashMufattish',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD14Q0KeuYs0CHDUsj2yN767zZkZ-SWjP0',
    appId: '1:449239285389:web:5cd641c457171fd98facc4',
    messagingSenderId: '449239285389',
    projectId: 'inspecto-shield',
    authDomain: 'inspecto-shield.firebaseapp.com',
    storageBucket: 'inspecto-shield.firebasestorage.app',
    measurementId: 'G-ZSHLNHS68Z',
  );
}
